// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types to prevent TypeScript errors
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          subdomain: string
          logo_url: string | null
          primary_color: string
          status: 'active' | 'suspended' | 'inactive'
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          subdomain: string
          logo_url?: string | null
          primary_color?: string
          status?: 'active' | 'suspended' | 'inactive'
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          subdomain?: string
          logo_url?: string | null
          primary_color?: string
          status?: 'active' | 'suspended' | 'inactive'
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          tenant_id: string
          email: string
          first_name: string
          last_name: string
          role: 'super_admin' | 'admin' | 'manager' | 'staff' | 'agent'
          avatar_url: string | null
          phone: string | null
          is_active: boolean
          last_login: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          tenant_id: string
          email: string
          first_name: string
          last_name: string
          role?: 'super_admin' | 'admin' | 'manager' | 'staff' | 'agent'
          avatar_url?: string | null
          phone?: string | null
          is_active?: boolean
          last_login?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          email?: string
          first_name?: string
          last_name?: string
          role?: 'super_admin' | 'admin' | 'manager' | 'staff' | 'agent'
          avatar_url?: string | null
          phone?: string | null
          is_active?: boolean
          last_login?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          tenant_id: string
          customer_number: string
          first_name: string
          last_name: string
          email: string | null
          phone: string
          date_of_birth: string | null
          gender: string | null
          national_id: string | null
          address: string | null
          city: string | null
          state: string | null
          country: string
          occupation: string | null
          employer: string | null
          monthly_income: number | null
          kyc_status: 'pending' | 'verified' | 'rejected' | 'expired'
          kyc_documents: Json
          credit_score: number
          tier: 'bronze' | 'silver' | 'gold' | 'platinum'
          profile_image: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          customer_number: string
          first_name: string
          last_name: string
          email?: string | null
          phone: string
          date_of_birth?: string | null
          gender?: string | null
          national_id?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          country?: string
          occupation?: string | null
          employer?: string | null
          monthly_income?: number | null
          kyc_status?: 'pending' | 'verified' | 'rejected' | 'expired'
          kyc_documents?: Json
          credit_score?: number
          tier?: 'bronze' | 'silver' | 'gold' | 'platinum'
          profile_image?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          customer_number?: string
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string
          date_of_birth?: string | null
          gender?: string | null
          national_id?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          country?: string
          occupation?: string | null
          employer?: string | null
          monthly_income?: number | null
          kyc_status?: 'pending' | 'verified' | 'rejected' | 'expired'
          kyc_documents?: Json
          credit_score?: number
          tier?: 'bronze' | 'silver' | 'gold' | 'platinum'
          profile_image?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      // Add other table types as needed
      [key: string]: any
    }
    Views: {
      [key: string]: never
    }
    Functions: {
      [key: string]: never
    }
    Enums: {
      [key: string]: never
    }
  }
}

